version: '3.8'

services:
  # Base de dades PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: dashboard-postgres
    environment:
      POSTGRES_DB: dashboard_assoliments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dashboard-network
    restart: unless-stopped

  # Aplicació Node.js
  app:
    build: .
    container_name: dashboard-app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dashboard_assoliments
      DB_USER: postgres
      DB_PASSWORD: postgres123
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - dashboard-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:

networks:
  dashboard-network:
    driver: bridge 