services:
  - type: web
    name: dashboard-assoliments
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: dashboard-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dashboard-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: dashboard-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: dashboard-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dashboard-postgres
          property: password

databases:
  - name: dashboard-postgres
    databaseName: dashboard_assoliments
    user: dashboard_user
    plan: starter 