services:
  - type: web
    name: dashboard-assoliments
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: node render-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        value: dpg-d1t0j4er433s73eraf60-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: assoliments_db
      - key: DB_USER
        value: assoliments_db_user
      - key: DB_PASSWORD
        value: AfS2hZUG6ovRKpqLlq3W7UNXJJPg0Rrh
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: UPLOAD_MAX_SIZE
        value: 10485760 